notifications:
  email: false

before_install:
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.11.1_linux_amd64.zip
  - sudo unzip terraform_0.11.1_linux_amd64.zip

script:
  - ./terraform init
  - ./terraform fmt
  - ./terraform plan
